modLoader="javafml"
loaderVersion="${loader_version_range}"
license="AGPL3"

[[mods]]
    modId="clod"
    version="${neoverse_version}"
    displayName="Neoverse"
    description='''Adds multiple dimensions to minecraft'''
